IMPORT PANDAS

In [4]:
import pandas as pd
import numpy as np

CREATE DATAFRAME

In [35]:
df = pd.DataFrame([1,2,3,4,5 ], columns=["values"])
print(df)

   values
0       1
1       2
2       3
3       4
4       5

In [37]:
data ={
    'Name':['khushbu', 'sneha', 'priya', 'snehal', 'priyanka'],
    'Age':[20, 21, 22, 23, 24],
    'Salary':[10000, 20000, 30000, 40000, 50000]
}

In [38]:
df = pd.DataFrame(data)
print(df)

       Name  Age  Salary
0   khushbu   20   10000
1     sneha   21   20000
2     priya   22   30000
3    snehal   23   40000
4  priyanka   24   50000

BASIC DATAFRAME UNDERSTANDING

In [20]:
df.head(2)

      Name  Age  Salary
0  khushbu   20   10000
1    sneha   21   20000

In [15]:
df.tail(2)

       Name  Age  Salary
3    snehal   23   40000
4  priyanka   24   50000

In [16]:
df.shape

(5, 3)

In [17]:
df.columns

Index(['Name', 'Age', 'Salary'], dtype='str')

In [29]:
df.rename(columns={'Salary':'Monthly_salary'}, inplace=True)
print(df)

       Name  Age  Monthly_salary
0   khushbu   20           10000
1     sneha   21           20000
2     priya   22           30000
3    snehal   23           40000
4  priyanka   24           50000

In [30]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Name            5 non-null      str
 1   Age             5 non-null      int64
 2   Monthly_salary  5 non-null      int64
dtypes: int64(2), str(1)
memory usage: 252.0 bytes

In [31]:
df.describe()

             Age  Monthly_salary
count   5.000000        5.000000
mean   22.000000    30000.000000
std     1.581139    15811.388301
min    20.000000    10000.000000
25%    21.000000    20000.000000
50%    22.000000    30000.000000
75%    23.000000    40000.000000
max    24.000000    50000.000000

SAVE AND LOAD DATA FROM CSV

In [ ]:
df.to_csv('data.csv', index=False)  #exporting the data to a CSV file

In [ ]:
load_dataframe=pd.read_csv('data.csv')   #importing the data from a CSV file
print(load_dataframe)

       Name  Age  Salary
0   khushbu   20   10000
1     sneha   21   20000
2     priya   22   30000
3    snehal   23   40000
4  priyanka   24   70000

ROW COLUMS - SELECTION

In [50]:
# SELECT COLUMNS
df['Name']

0     khushbu
1       sneha
2       priya
3      snehal
4    priyanka
Name: Name, dtype: str

In [53]:
#SELECT ROWS
#loc - index name based selection
df.loc[df.Name=='khushbu']
df.loc[df.Age>22]

       Name  Age  Salary
3    snehal   23   40000
4  priyanka   24   50000

In [54]:
#iloc - index position based selection
df.iloc[0:3]

      Name  Age  Salary
0  khushbu   20   10000
1    sneha   21   20000
2    priya   22   30000