IMPORT PANDAS

In [4]:
import pandas as pd
import numpy as np

CREATE DATAFRAME

In [35]:
df = pd.DataFrame([1,2,3,4,5 ], columns=["values"])
print(df)

   values
0       1
1       2
2       3
3       4
4       5

In [64]:
data ={
    'Name':['khushbu', 'sneha', 'priya', 'snehal', 'priyanka'],
    'Age':[20, 21, 22, 23, 24],
    'Salary':[70000, 20000, 30000, 40000, 50000]
}

In [65]:
df = pd.DataFrame(data)
print(df)

       Name  Age  Salary
0   khushbu   20   70000
1     sneha   21   20000
2     priya   22   30000
3    snehal   23   40000
4  priyanka   24   50000

BASIC DATAFRAME UNDERSTANDING

In [66]:
df.head(2)

      Name  Age  Salary
0  khushbu   20   70000
1    sneha   21   20000

In [67]:
df.tail(2)

       Name  Age  Salary
3    snehal   23   40000
4  priyanka   24   50000

In [68]:
df.shape

(5, 3)

In [69]:
df.columns

Index(['Name', 'Age', 'Salary'], dtype='str')

In [70]:
df.rename(columns={'Salary':'Monthly_salary'}, inplace=True)
print(df)

       Name  Age  Monthly_salary
0   khushbu   20           70000
1     sneha   21           20000
2     priya   22           30000
3    snehal   23           40000
4  priyanka   24           50000

In [71]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Name            5 non-null      str
 1   Age             5 non-null      int64
 2   Monthly_salary  5 non-null      int64
dtypes: int64(2), str(1)
memory usage: 252.0 bytes

In [72]:
df.describe()

             Age  Monthly_salary
count   5.000000        5.000000
mean   22.000000    42000.000000
std     1.581139    19235.384062
min    20.000000    20000.000000
25%    21.000000    30000.000000
50%    22.000000    40000.000000
75%    23.000000    50000.000000
max    24.000000    70000.000000

SAVE AND LOAD DATA FROM CSV

In [96]:
df.to_csv('data.csv', index=False)  #exporting the data to a CSV file

In [97]:
load_dataframe=pd.read_csv('data.csv')   #importing the data from a CSV file
print(load_dataframe)

       Name  Age  Monthly_salary       Team
0   khushbu   20           70000         HR
1     sneha   21           20000         IT
2     priya   22           30000    Finance
3    snehal   23           40000  Marketing
4  priyanka   24           50000      Sales
5     Rohit   25           60000         HR
6     Rohit   25           60000         HR
7      Mahi   26           70000         IT
8    Anjali   25           60000         IT

ROW COLUMS - SELECTION

In [75]:
# SELECT COLUMNS
df['Name']

0     khushbu
1       sneha
2       priya
3      snehal
4    priyanka
Name: Name, dtype: str

In [76]:
#SELECT ROWS
#loc - index name based selection
df.loc[df.Name=='khushbu']
df.loc[df.Age>22]

       Name  Age  Monthly_salary
3    snehal   23           40000
4  priyanka   24           50000

In [77]:
#iloc - index position based selection
df.iloc[0]

Name              khushbu
Age                    20
Monthly_salary      70000
Name: 0, dtype: object

FILTER DATAFRAME

In [78]:
df[df['Age']>21]

       Name  Age  Monthly_salary
2     priya   22           30000
3    snehal   23           40000
4  priyanka   24           50000

In [79]:
df.where(df['Age']>21)

       Name   Age  Monthly_salary
0       NaN   NaN             NaN
1       NaN   NaN             NaN
2     priya  22.0         30000.0
3    snehal  23.0         40000.0
4  priyanka  24.0         50000.0

ROW AND COLUMN - OPERATION

In [80]:
df

       Name  Age  Monthly_salary
0   khushbu   20           70000
1     sneha   21           20000
2     priya   22           30000
3    snehal   23           40000
4  priyanka   24           50000

In [81]:
#add new column
df['Team']=['HR', 'IT', 'Finance', 'Marketing', 'Sales']
df

       Name  Age  Monthly_salary       Team
0   khushbu   20           70000         HR
1     sneha   21           20000         IT
2     priya   22           30000    Finance
3    snehal   23           40000  Marketing
4  priyanka   24           50000      Sales

In [94]:
#add new row
df.loc[5] = ['Rohit', 25, 60000, 'HR']
df.loc[6] = ['Rohit', 25, 60000, 'HR']
df.loc[7] =['Mahi', 26, 70000, 'IT']
df

       Name  Age  Monthly_salary       Team
0   khushbu   20           70000         HR
1     sneha   21           20000         IT
2     priya   22           30000    Finance
3    snehal   23           40000  Marketing
4  priyanka   24           50000      Sales
5     Rohit   25           60000         HR
6     Rohit   25           60000         HR
7      Mahi   26           70000         IT
8    Anjali   25           60000         IT

In [95]:
len(df)

9